version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    networks:
      - iqraschool
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: production
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
    container_name: nextjs_app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - iqraschool
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  iqraschool:
    driver: bridge